name: Build
run-name: ${{ github.event.inputs.job_to_run && format('Build {0}', github.event.inputs.job_to_run) }}

concurrency:
  group: build-eden-${{ github.ref }}-${{ github.event.inputs.job_to_run || github.event_name }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      job_to_run:
        type: choice
        description: 'windows?'
        options: [windows]
        default: 'windows'

jobs:
  windows:
    runs-on: ${{ matrix.runs-on }}
    name: "Windows"
    strategy:
      fail-fast: false
      matrix:
        include:
           - toolchain: MSVC
             optimize: normal
             arch: x86_64
             runs-on: windows-latest
    defaults:
      run:
        shell: ${{ 'bash {0}' }}
    env:
      TOOLCHAIN: ${{ matrix.toolchain }}
      ARCH: ${{ matrix.arch }}
      OPTIMIZE: ${{ matrix.optimize }}
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - uses: actions/checkout@v6.0.2

      - name: MSVC
        uses: Eden-CI/msvc-dev-cmd@master
        with:
          arch: ${{ matrix.arch }}

      - name: Vulkan
        shell: powershell
        run: |
          ./vulkan.ps1

      - name: Sccache
        uses: Eden-CI/sccache-action@master
        with:
          disable_annotations: true

      - name: Clone
        run: |
          git clone 'https://git.eden-emu.dev/eden-emu/eden.git' ./eden
          cd ./eden
          echo "VERSION=$(git rev-list --count HEAD)" >> "${GITHUB_ENV}"

      - name: Compile
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v7.0.1
        with:
          name: eden
          path: eden/build/bin/
